name: klaytn-safe-react dev deploy workflow
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN_DEV }}
          role-session-name: SessionForKlaytnActions
          aws-region: ${{ secrets.AWS_REGION_DEV }}

      - name: Installing Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

#      - name: Installing dependencies
#        run: |
#          yarn install
#          cp -r ./safe-deployment-assets/* ./node_modules/@gnosis.pm/safe-deployments/dist/assets/
#          cp -r ./safe-deployment-assets/* ./node_modules/@gnosis.pm/safe-core-sdk/node_modules/@gnosis.pm/safe-deployments/dist/assets/
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile && yarn after-install
      - name: Build static files
        env:
          NEXT_PUBLIC_GATEWAY_URL_PRODUCTION: ${{ secrets.NEXT_PUBLIC_GATEWAY_URL_PRODUCTION }}
        run: yarn build

      - name: Sync to S3 bucket and validation cloudfront
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET_DEV }}
          CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID_DEV }}
        run: |
          aws s3 sync ./build $S3_BUCKET --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
